# Build and deploy the website to Vercel.
#
# This workflow is run on every commit to the main branch.
#
name: Vercel deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vercel_project: [smallcaps, ok]

    steps:
      - uses: actions/checkout@v2

      - name: Link project
        run: vercel link --project ${{ matrix.vercel_project }} --yes --token ${{ secrets.VERCEL_ACCOUNT_TOKEN }}

      - name: Deploy
        run: |
          vercel --token ${{ secrets.VERCEL_ACCOUNT_TOKEN }} deploy --prod
